edition = "2021"
max_width = 128
use_field_init_shorthand = true
newline_style = "Unix"
format_strings = true
comment_width = 128
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
normalize_comments = true
normalize_doc_attributes = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_impl_items = true
reorder_imports = true
tab_spaces = 2
wrap_comments = true
use_small_heuristics = "Max"
